version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10-browsers

    working_directory: ~/repo/packages/web

    steps:
      - checkout
      - run: yarn install
      - run: yarn test
