version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/typeracer

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "packages/web/package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "packages/web/package.json" }}

      - run: yarn test
